Transfer to lightning with dbv0
ITMO-NSS-team/GAMLET pull request #45
Opened 2023-07-27 18:09 UTC by ShikovEgor

Surrogate model based on GNN for FEDOT.

Files:
meta_automl/surrogate/encoders - encoder models for pipelines/datasets
meta_automl/surrogate/data - data preparation for GraphTransformer
meta_automl/surrogate/models - surrogate model combining pipeline and dataset encoder to get pipeline score on dataset
meta_automl/surrogate/training - training/tuning pipelines
Examples:
examples/6_gnn_surrogate

2023-08-08 12:24 UTC, aPovidlo requested changes

2023-08-08 12:24 UTC, aPovidlo commented on meta_automl/data_preparation/meta_features_extractors/openml_dataset_meta_features_extractor.py
> +    meta_features_data_columns: List of names of meta-features to be extracted.
Думаю, что стоит добавить список из доступных и краткое описание для каждого из них

2023-08-08 12:24 UTC, aPovidlo commented on meta_automl/data_preparation/pipeline_features_extractors/fedot_pipeline_features_extractor.py
> +        # '': '',  # Empty string indicates that the node means <no_operation> as https://t.me/FGksjp67 requested.
"Замечательный" и ненужный комментарий 😠

2023-08-08 12:24 UTC, aPovidlo commented on meta_automl/data_preparation/pipeline_features_extractors/fedot_pipeline_features_extractor.py
> +    }
Возможно ли расширение данного списка за счет появления новых операций в FEDOT?

2023-08-11 13:18 UTC, ShikovEgor commented on meta_automl/data_preparation/meta_features_extractors/openml_dataset_meta_features_extractor.py
> +    meta_features_data_columns: List of names of meta-features to be extracted.
Я бы не стал этого делать, т.к. класс нужно будет в целом переписать. Сейчас подгружаются предрассчитанные признаки из OpenML - в таком случае нельзя посчитать мета-признаки для датасета, который не в OpenML. Лучше считать их самим, ничего сложного там нет.

2023-08-11 13:20 UTC, ShikovEgor commented on meta_automl/data_preparation/pipeline_features_extractors/fedot_pipeline_features_extractor.py
> +    }
да, конечно

2023-08-11 18:31 UTC, ChernyakKonstantin requested changes

2023-08-11 18:31 UTC, ChernyakKonstantin commented on examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py
> +#     )
Может убрать?

2023-08-11 18:31 UTC, ChernyakKonstantin commented on meta_automl/data_preparation/meta_features_extractors/openml_dataset_meta_features_extractor.py
> +            return None # ?? self.meta_features
```suggestion
    def _get_features(self, dataset_id: int) -> Dict[str, int]:
        dataset_info = openml.datasets.list_datasets([dataset_id,], output_format="dataframe").iloc[0].to_dict()
        meta_features = {}
        for key in self.meta_features_data_columns:
            try:
                meta_features[key] = dataset_info[key]
            except KeyError:
                 meta_features[key] = -1
        return meta_features
```

2023-08-11 18:31 UTC, ChernyakKonstantin commented on meta_automl/data_preparation/pipeline_features_extractors/fedot_pipeline_features_extractor.py
> +        # '': '',  # Empty string indicates that the node means <no_operation> as https://t.me/FGksjp67 requested.
Ну да, с учетом что его по какой-то причине не удалось сделать, если ничего не изменилось.
Заменить на: 
```suggestion
        # '': '',  # Empty string indicates that the node means <no_operation> 
```
?

2023-08-11 18:31 UTC, ChernyakKonstantin commented on meta_automl/meta_algorithm/model_advisors/surrogate_advisor.py
> +        # нужно переписать, когда будет работающий FeaturesExtractor, который будет принимать DataFrame, а не dataset_id !!!!
Не помню, кто такой комент оставил. Как-то изменить?

2023-08-11 18:31 UTC, ChernyakKonstantin commented on meta_automl/surrogate/datasets/data.py
> +class PairDataset(SingleDataset):
Думаю, нужно добавить описание.

2023-08-11 18:31 UTC, ChernyakKonstantin commented on meta_automl/surrogate/datasets/data.py
> +class SingleDataset(Dataset):
Думаю, нужно добавить описание.

2023-08-11 18:31 UTC, ChernyakKonstantin commented on meta_automl/surrogate/datasets/data.py
> +
Думаю, нужно добавить описание.

2023-08-11 18:31 UTC, ChernyakKonstantin commented on meta_automl/surrogate/datasets/dataset_generate.py
> +class KnowledgeBaseToDataset:
Думаю, нужно добавить описание к аргументам.

2023-08-11 18:31 UTC, ChernyakKonstantin commented on meta_automl/surrogate/datasets/dataset_generate.py
> +        exclude_datasets: Optional[List[str]] = None,  # In accordance to @MorrisNein message in chat
Если для внутреннего пользования больше не нужно:
```suggestion
        exclude_datasets: Optional[List[str]] = None
```

2023-08-11 18:31 UTC, ChernyakKonstantin commented on meta_automl/surrogate/encoders/graph_transformer/gnn_layers.py
> +        # TODO: ask @eegoro to fix it
Все еще актуально?

2023-08-11 18:31 UTC, ChernyakKonstantin commented on notebooks/test_population_ranking_get_data.ipynb
Удалить

2023-08-11 18:31 UTC, ChernyakKonstantin commented on notebooks/test_population_ranking.ipynb
Удалить

2023-08-11 18:31 UTC, ChernyakKonstantin commented on notebooks/get_dataset_from_knowledge_base_v0.ipynb
Удалить. Дубликат класса KnowledgeBaseToDataset и, соответственно, scripts/generate_training_dataset.py

2023-08-11 20:28 UTC, ShikovEgor commented on examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py
> +#     )
да

2023-08-11 20:49 UTC, ShikovEgor commented on thegolem/data_pipeline_surrogate.py
> +        pipeline_features.x = pipeline_features.x.view(-1)  # change if use model's hyperparameters!!!!
можно на всякий случай

2023-08-11 20:50 UTC, ShikovEgor commented on scripts/generate_training_dataset.py
оставить тут.

2023-08-11 21:05 UTC, ShikovEgor commented on meta_automl/meta_algorithm/model_advisors/surrogate_advisor.py
> +        # нужно переписать, когда будет работающий FeaturesExtractor, который будет принимать DataFrame, а не dataset_id !!!!
Это я. Суть в том, что сейчас в логике OpenMLFeatureExtractor невозможен расчет признаков из датафрейма. Они берутся готовые. Поэтому для датасета не из OpenML невозможно провести расчет. Как вариант, можно заменить OpenMLFeatureExtractor  на PyMFEExtarctor. Сейчас как раз разбираемся с ним.

2023-08-11 21:06 UTC, ShikovEgor commented on meta_automl/surrogate/datasets/data.py
> +class PairDataset(SingleDataset):
пропустил, сделаю

2023-08-14 11:25 UTC, aPovidlo commented on scripts/main.py
> +sys.path.append(os.getcwd())
@ChernyakKonstantin А что это и зачем?

2023-08-14 17:14 UTC, ChernyakKonstantin commented
fedot 0.7.1 требует thegolem==0.3.1, в то время как в requirements.txt указан thegolem==0.3.2.

2023-08-14 18:57 UTC, ShikovEgor reviewed
Версия GOLEM 0.3.1 выдавала ошибки:
https://t.me/FEDOT_helpdesk/1361
Насчет зависимости в FEDOT - возможно там нужно обновить.
Кстати вопрос по requirements.txt - в каком он у нас формате? Почему он не в каждом редакторе открывается?

2023-09-26 14:03 UTC, MorrisNein requested changes

2023-09-26 14:03 UTC, MorrisNein commented on meta_automl/meta_algorithm/model_advisors/surrogate_advisor.py
> +    def predict(self, dataset: pd.DataFrame, k: int = 5) -> List[List[Model]]:
Здесь Model это совокупность предиктора (например, пайплайна) и некоторой метрики (в данном случае скора?)

Как я понял, сейчас вместо этого возвращаются сами пайплайны. Если это так, поправьте под интерфейс, пожалуйста

2023-09-29 13:24 UTC, ShikovEgor commented on meta_automl/data_preparation/pipeline_features_extractors/fedot_pipeline_features_extractor.py
В идеале да. Думаю, это не очень приоритетно, но стоит отметить на будущее.

2023-09-29 15:13 UTC, pep8speaks commented
Hello @ShikovEgor! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`examples/4_advising_models/advise_by_surrogate.py`](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py):

> [Line 1:11](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L1): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 2:21](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L2): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 3:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L3): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 3:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'pandas as pd' imported but unused
> [Line 5:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L5): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 5:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L5): [F401](https://duckduckgo.com/?q=pep8%20F401) 'meta_automl.data_preparation.dataset.OpenMLDataset' imported but unused
> [Line 6:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L6): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 7:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L7): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 9:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L9): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 16:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L16): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 20:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L20): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 21:67](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L21): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 21:69](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L21): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 27:18](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/4_advising_models/advise_by_surrogate.py#L27): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py`](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py):

> [Line 6:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L6): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 6:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L6): [F401](https://duckduckgo.com/?q=pep8%20F401) 'thegolem.data_pipeline_surrogate.DataPipelineSurrogate' imported but unused
> [Line 8:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L8): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 8:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L8): [F401](https://duckduckgo.com/?q=pep8%20F401) 'meta_automl.data_preparation.feature_preprocessors.FeaturesPreprocessor' imported but unused
> [Line 9:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L9): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 9:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L9): [F401](https://duckduckgo.com/?q=pep8%20F401) 'meta_automl.data_preparation.meta_features_extractors.OpenMLDatasetMetaFeaturesExtractor' imported but unused
> [Line 10:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L10): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 11:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L11): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 12:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L12): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 14:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L14): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 29:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L29): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 35:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L35): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 36:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L36): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 38:5](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/accessing_pipeline_dataset_encoders.py#L38): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)

* In the file [`examples/6_gnn_surrogate/surrogate_optimizer_example.py`](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/97c167f93ee759fd375aa0a3899524c57a60b749/examples/6_gnn_surrogate/surrogate_optimizer_example.py):

> [Line 5:1](https://github.com/ITMO-NSS-team/MetaF [...]

2023-10-24 11:58 UTC, MorrisNein requested changes

2023-10-24 11:58 UTC, MorrisNein commented on .gitignore
> +/experiments
По обсуждению с @ChernyakKonstantin, решили исключить эту папку из .gitignore, использовать для логов другую директорию. Потому что в моей ветке используется эта же директория

2023-10-24 12:04 UTC, MorrisNein requested changes

2023-10-24 12:04 UTC, MorrisNein commented on meta_automl/meta_algorithm/model_advisors/surrogate_advisor.py
> +        return best_models
Этот метод можно назвать predict_single, а в predict циклом вызвать его. Потому что интерфейс подразумевает построение предсказания на списке датасетов.

2023-10-24 12:11 UTC, MorrisNein commented on scripts/main.py
> +sys.path.append(os.getcwd())
Хорошее решение, взял на заметку. Я обычно руками в path сервера прописываю перед запуском скриптов.

@aPovidlo это добавление корня проекта в PYTHONPATH, чтобы можно было импортировать его объекты. В PyCharm это не нужно делать, потому что корень проекта по умолчанию входит в PYTHONPATH. На сервере же импорты изначально вызывают ошибку, если этого не сделать.

2023-10-25 10:08 UTC, ShikovEgor commented on meta_automl/meta_algorithm/model_advisors/surrogate_advisor.py
> +        return best_models
Исправил

2023-10-25 10:08 UTC, ShikovEgor commented on .gitignore
> +/experiments
Исправил

2023-10-25 10:14 UTC, MorrisNein approved these changes
После фикса конфликтов можно вливать

2023-10-25 12:39 UTC, nicl-nno approved these changes

2023-10-25 20:37 UTC, DRMPN commented
Пофиксил E402 для файла `examples/4_advising_models/advise_by_surrogate.py`
У себя локально использую Black и iSort.
Бот изменил свой комментарий в _**Comment last updated at 2023-10-25 20:30:07 UTC**_

![image](https://github.com/ITMO-NSS-team/GAMLET/assets/61294398/7d54a116-66e8-478a-863e-542a704e9b64)

2023-10-27 12:45 UTC, MorrisNein commented
@ChernyakKonstantin, @aPovidlo жмякайте аппрув, если больше нет замечаний

2023-10-27 13:13 UTC, merged