Add docstrings to existing code.
ITMO-NSS-team/GAMLET pull request #48
Opened 2023-08-06 22:42 UTC by DRMPN

First step of adding docstrings to existing code base.

2023-08-06 22:52 UTC, DRMPN commented on meta_automl/meta_algorithm/model_advisors/model_advisor.py
Решил делать по одному файлу для простоты и удобства проверки.
Нужна помощь в корректном написании, ибо не все могу правильно понять и прочитать.

2023-08-08 12:18 UTC, MorrisNein reviewed
По формату всё отлично. Единственное, предлагаю не дублировать в докстринг типы аргументов.

2023-08-08 19:12 UTC, DRMPN commented
> По формату всё отлично. Единственное, предлагаю не дублировать в докстринг типы аргументов.

Хммм, ну да, соглашусь, это наверное лишнее.

2023-08-08 19:18 UTC, DRMPN commented on meta_automl/meta_algorithm/model_advisors/model_advisor.py
У меня black formatter стоит

2023-08-13 00:29 UTC, DRMPN reviewed
Добавил докстринги для модуля `model_advisors`.
Опирался на стиль EPDE и sklearn, хотел бы советы и рекомендации по оформлению пока ушел не так далеко.
Исправления приветствуются, т.к. мог не совсем точно описать что-либо.

2023-08-13 12:02 UTC, algormx requested changes
Для того, чтобы было проще документировать было бы кстати писать спецификации(например, с помощью того же TDD).

2023-08-20 18:21 UTC, DRMPN reviewed
Постарался исправить

2023-08-20 18:21 UTC, DRMPN commented on meta_automl/meta_algorithm/datasets_similarity_assessors/model_based_similarity_assessors.py
> +            Optionally when 'return_distance' == True returns measure of similarity to the neighbors of each point.
Может быть, взял за основу описание из [докуменатции sklearn.](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.NearestNeighbors.html#sklearn.neighbors.NearestNeighbors.kneighbors)

2023-08-20 21:07 UTC, algormx commented on meta_automl/meta_algorithm/datasets_similarity_assessors/model_based_similarity_assessors.py
> +            Optionally when 'return_distance' == True returns measure of similarity to the neighbors of each point.
Раз это параметр для внешнего модуля, то я бы брал таковые как kwargs и отсылал к их документации.

2023-08-20 21:09 UTC, algormx commented on meta_automl/meta_algorithm/model_advisors/diverse_fedot_pipeline_advisor.py
> +    """Diverse FEDOT pipeline advisor.
Вероятно, @MorrisNein лучше знать.

2023-08-20 21:12 UTC, algormx commented on meta_automl/meta_algorithm/datasets_similarity_assessors/datasets_similarity_assessor.py
> +    Optionally, it can also return a measure of similarity (or distance) between
Лучше discovers опустив lists.

2023-08-21 08:35 UTC, DRMPN commented on meta_automl/meta_algorithm/datasets_similarity_assessors/model_based_similarity_assessors.py
> +            Optionally when 'return_distance' == True returns measure of similarity to the neighbors of each point.
Добавил ссылку на документацию и изменил код на kwargs (а потом обратно).
При выполнении 3-го и 4-го примера в examples появляется ошибка.
Вижу два варианта: либо каждый раз при вызове `predict()` заносить `return_distance=False`, либо поставить в функцию эту опцию по дефолту.

Изначально код написан по второму варианту, поэтому пока что не вижу смысла добавлять **kwargs в этом случае, ибо исходная функция принимает всего 3 аргумента, 2 из которых мы уже задаем.

2023-08-23 16:08 UTC, algormx commented on meta_automl/meta_algorithm/model_advisors/model_advisor.py
> +            similar_dataset_ids: Iterable object of dataset ids.
ids_of_similar_datasets

2023-08-23 16:14 UTC, algormx reviewed
Впринципе можно мерджить при approval-е от @MorrisNein, лучше продокументировать @DRMPN будет сложно.

2023-09-05 10:36 UTC, MorrisNein approved these changes

2023-09-05 10:36 UTC, MorrisNein commented on meta_automl/meta_algorithm/model_advisors/diverse_fedot_pipeline_advisor.py
> +    """Diverse FEDOT pipeline advisor.
Согласен. Но не в этом PR.

2023-09-29 07:55 UTC, pep8speaks commented
Hello @DRMPN! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`docs/source/conf.py`](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/de69c387beef1d99c15bbe36eb06d56eee00a2f1/docs/source/conf.py):

> [Line 19:1](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/de69c387beef1d99c15bbe36eb06d56eee00a2f1/docs/source/conf.py#L19): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file

2023-10-02 10:05 UTC, DRMPN commented
Собрал и сделал авто-документацию, выложил на readthedocs:
Ссылка с информацией - https://readthedocs.org/projects/metafedot/
Сама документация доступна - https://metafedot.readthedocs.io/en/latest/

2023-10-02 12:31 UTC, MorrisNein approved these changes
Отлично сделано, спасибо!

2023-10-02 12:31 UTC, MorrisNein commented on docs/source/conf.py
> +# napoleon_include_init_with_doc = True
Это уже можно убрать?

2023-10-02 14:32 UTC, DRMPN commented on docs/source/conf.py
> +# napoleon_include_init_with_doc = True
Да, можно убрать

2023-10-05 18:49 UTC, csarx approved these changes

2023-10-06 10:35 UTC, aPovidlo requested changes

2023-10-06 10:35 UTC, aPovidlo commented on docs/source/about.rst
> +The MetaFEDOT is developed and maintained by the `NSS Lab <https://itmo-nss-team.github.io/>`__ team.
Думаю, что нужно изменить везде названия на актуальное

2023-10-06 10:35 UTC, aPovidlo commented on docs/source/metafedot/metafedot.rst
> +Datasets loader & Dataset
Тут loader с маленькой, а ниже с большой

2023-10-06 10:36 UTC, aPovidlo commented
А добавление докстрингов для кода это для другого PR или этого?

2023-10-06 13:12 UTC, DRMPN commented on docs/source/about.rst
> +The MetaFEDOT is developed and maintained by the `NSS Lab <https://itmo-nss-team.github.io/>`__ team.
ахаха, хорошо

2023-10-06 13:13 UTC, DRMPN commented
> А добавление докстрингов для кода это для другого PR или этого?

для этого

2023-10-08 10:59 UTC, DRMPN commented
Изменил имя в документации на GAMLET

2023-10-08 18:38 UTC, MorrisNein commented on docs/source/gamlet/installation.rst
> +  | ``$ pip install GAMLET``
Так и ставится, заглавными? Предлагаю зарегистрировать маленькими, если имя не занято

2023-10-09 07:46 UTC, DRMPN commented on docs/source/gamlet/installation.rst
> +  | ``$ pip install GAMLET``
Хорошо, будет lowercase в pypi, предлагаю в другом PR это сделать.

2023-10-09 13:17 UTC, MorrisNein approved these changes

2023-10-12 19:24 UTC, merged