Add timeseries branch
ITMO-NSS-team/GAMLET pull request #56
Opened 2023-09-18 07:36 UTC by valer1435

Add feature extraction from time series by fedot.Industrial

2023-09-26 12:40 UTC, MorrisNein requested changes

2023-09-26 12:40 UTC, MorrisNein commented on meta_automl/data_preparation/meta_features_extractors/time_series_meta_features_extractor.py
> +                meta_features[idx] = self._extractor.root_node.predict(input_data).predict[0]
Для TS экстрактора подразумевается использование кэша? Как [вот здесь](https://github.com/ITMO-NSS-team/MetaFEDOT/blob/a3a61f1ed850c6bda9e2d8ff6fe8242eec174c65/meta_automl/data_preparation/meta_features_extractors/pymfe_extractor.py#L44-L47)

2023-09-26 12:40 UTC, MorrisNein commented on examples/5_visualisation/visualisation_ts_embeddings.py
> +    meta_features = pd.read_csv('../../data/knowledge_base_time_series_0/meta_features_ts.csv')
С таким экстракторы справляются по-умолчанию, если подрубить использование кэша

2023-09-26 12:40 UTC, MorrisNein commented on examples/5_visualisation/visualisation_ts_embeddings.py
> +    # # plt.plot(variants, res)
Необязательная часть примера?

2023-09-26 12:42 UTC, MorrisNein commented
Извиняюсь за задержку. Очень хорошо написано, соблюдён стиль остального фреймворка. Единственное, предлагаю сразу добавить так же кэширование

2023-10-11 09:36 UTC, valer1435 commented
> Извиняюсь за задержку. Очень хорошо написано, соблюдён стиль остального фреймворка. Единственное, предлагаю сразу добавить так же кэширование

Действительно стоит, но я пока не разбирался как именно оно работает и что кэширует. Можешь подробнее описать?

2023-10-12 12:48 UTC, MorrisNein commented
Ответил @valer1435 в ЛС

2023-10-12 19:10 UTC, pep8speaks commented
Hello @valer1435! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`examples/0_loading_data/load_time_series_datasets.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/0_loading_data/load_time_series_datasets.py):

> [Line 1:1](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/0_loading_data/load_time_series_datasets.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'meta_automl.data_preparation.datasets_loaders.OpenMLDatasetsLoader' imported but unused

* In the file [`examples/2_extracting_datasets_meta_features/extract_features_from_ts.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/2_extracting_datasets_meta_features/extract_features_from_ts.py):

> [Line 20:1](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/2_extracting_datasets_meta_features/extract_features_from_ts.py#L20): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1



* In the file [`examples/4_advising_models/advice_ts_models_from_similar_datasets.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/4_advising_models/advice_ts_models_from_similar_datasets.py):

> [Line 24:5](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/4_advising_models/advice_ts_models_from_similar_datasets.py#L24): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'



* In the file [`examples/6_inference/inference_ts_knn.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/6_inference/inference_ts_knn.py):

> [Line 1:1](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/6_inference/inference_ts_knn.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'os' imported but unused
> [Line 8:1](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/6_inference/inference_ts_knn.py#L8): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.pipelines.pipeline_builder.PipelineBuilder' imported but unused
> [Line 10:1](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/6_inference/inference_ts_knn.py#L10): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.pipelines.tuning.tuner_builder.TunerBuilder' imported but unused
> [Line 12:1](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/6_inference/inference_ts_knn.py#L12): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.repository.quality_metrics_repository.RegressionMetricsEnum' imported but unused
> [Line 15:1](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/6_inference/inference_ts_knn.py#L15): [F401](https://duckduckgo.com/?q=pep8%20F401) 'golem.core.tuning.simultaneous.SimultaneousTuner' imported but unused
> [Line 34:5](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/6_inference/inference_ts_knn.py#L34): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 93:9](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/6_inference/inference_ts_knn.py#L93): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'train_data' is assigned to but never used
> [Line 96:9](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/6_inference/inference_ts_knn.py#L96): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'test_data' is assigned to but never used
> [Line 118:1](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/examples/6_inference/inference_ts_knn.py#L118): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1









* In the file [`meta_automl/data_preparation/meta_features_extractors/time_series/time_series_meta_features_extractor.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/meta_automl/data_preparation/meta_features_extractors/time_series/time_series_meta_features_extractor.py):

> [Line 37:26](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/meta_automl/data_preparation/meta_features_extractors/time_series/time_series_meta_features_extractor.py#L37): [F541](https://duckduckgo.com/?q=pep8%20F541) f-string is missing placeholders





* In the file [`test/unit/datasets/conftest.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/test/unit/datasets/conftest.py):

> [Line 25:1](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/test/unit/datasets/conftest.py#L25): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`test/unit/datasets/test_datasets_loaders.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/test/unit/datasets/test_datasets_loaders.py):

> [Line 30:5](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/test/unit/datasets/test_datasets_loaders.py#L30): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'datasets' is assigned to but never used
> [Line 37:9](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/test/unit/datasets/test_datasets_loaders.py#L37): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'dataset' is assigned to but never used

* In the file [`test/unit/datasets/test_ts_dataset.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/test/unit/datasets/test_ts_dataset.py):

> [Line 6:1](https://github.com/ITMO-NSS-team/GAMLET/blob/c32e1b218857dbca0f5711db57bc6288d8f64743/test/unit/datasets/test_ts_dataset.py#L6): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)

2023-10-12 19:11 UTC, valer1435 commented on meta_automl/data_preparation/dataset/time_series_dataset.py
> +                                 'models', 'FEDOT', s + '.json'))
[Удалил](https://github.com/ITMO-NSS-team/GAMLET/pull/56/commits/fbee4189d093b178d39fa42124e164da514bbc13#diff-54045bca6b664aa459f1f265b2090364a33c68c7fa44ea9d51a75e494fcdec77R19-R20)

2023-10-12 19:11 UTC, valer1435 commented on meta_automl/data_preparation/meta_features_extractors/time_series_meta_features_extractor.py
> +                meta_features[idx] = self._extractor.root_node.predict(input_data).predict[0]
Добавил [кэш](https://github.com/ITMO-NSS-team/GAMLET/pull/56/commits/fbee4189d093b178d39fa42124e164da514bbc13#diff-f66a47f9c95eaccd587b3e3407ceac46966cb79e2aac7036f90bbbfef72e64f7R41)

2023-10-12 19:12 UTC, valer1435 commented on examples/5_visualisation/visualisation_ts_embeddings.py
> +    # # plt.plot(variants, res)
Теперь [неактуально](https://github.com/ITMO-NSS-team/GAMLET/pull/56/commits/fbee4189d093b178d39fa42124e164da514bbc13#diff-3afc350e125235cb23954b281ddfb96d36c7b16e9a046b81e730785388d7a98dR179)

2023-10-15 11:27 UTC, valer1435 commented
Обнаружил неизвестную проблему, из-за которой качество предсказания сильно упало (стало гораздо хуже :/ Не знаю, то ли это связано с индастриалом, то ли моя ошибка, но результаты продублировать не выходит

2023-10-18 13:22 UTC, MorrisNein requested changes

2023-10-18 13:22 UTC, MorrisNein commented on meta_automl/data_preparation/datasets_loaders/timeseries_dataset_loader.py
> +class TimeSeriesDatasetsLoader(CustomDatasetsLoader):
Стоит ли наследоваться от CustomDatasetLoader вместо абстрактного класса, если TimeSeriesDataset наследуется от абстрактного DatasetBase? У этого есть практическая значимость?

2023-10-18 13:22 UTC, MorrisNein commented on examples/6_inference/inference_ts_knn.py
> +        # #
Ты считаешь среднее расстояние от итогового решения до случайного графа из лучших? Уточни, пожалуйста, что это за метрика

Возможно, было бы надёжнее конструировать случайный граф? GOLEM, кажется, [так умеет](https://github.com/aimclub/GOLEM/pull/214#issuecomment-1755138911)

2023-10-18 13:49 UTC, valer1435 commented on test/data/cache/datasets/custom_dataset/M4_D152/model/0_pipeline_saved/0_pipeline_saved.json
Да

2023-10-19 18:01 UTC, valer1435 commented on meta_automl/data_preparation/datasets_loaders/timeseries_dataset_loader.py
> +class TimeSeriesDatasetsLoader(CustomDatasetsLoader):
Да, он наследует метод load()

2023-10-23 09:12 UTC, valer1435 commented on meta_automl/data_preparation/meta_features_extractors/time_series/time_series_meta_features_extractor.py
> +        meta_feature_names = np.arange(184)
Вынес https://github.com/ITMO-NSS-team/GAMLET/pull/56/commits/7e043ddffefd187a43480daefc733cde86077c92#diff-f66a47f9c95eaccd587b3e3407ceac46966cb79e2aac7036f90bbbfef72e64f7R19

2023-10-23 12:01 UTC, MorrisNein commented on meta_automl/data_preparation/datasets_loaders/timeseries_dataset_loader.py
> +class TimeSeriesDatasetsLoader(CustomDatasetsLoader):
В таком случае лучше перенести реализацию метода load() в абстрактный класс, и наследовать этот лоадер от него

2023-10-24 09:43 UTC, merged