Fix in get_n_best_fedot_performers args
ITMO-NSS-team/GAMLET pull request #64
Opened 2023-10-27 18:04 UTC by nicl-nno

2023-10-27 19:07 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`examples/4_advising_models/advise_models_from_similar_datasets.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/9c34dff8a27682b5ef05a0731718f4ea86cc0abd/examples/4_advising_models/advise_models_from_similar_datasets.py):

> [Line 45:1](https://github.com/ITMO-NSS-team/GAMLET/blob/9c34dff8a27682b5ef05a0731718f4ea86cc0abd/examples/4_advising_models/advise_models_from_similar_datasets.py#L45): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2023-10-27 21:10 UTC, MorrisNein requested changes

2023-10-27 21:10 UTC, MorrisNein commented on meta_automl/meta_algorithm/model_advisors/diverse_fedot_pipeline_advisor.py
> +                diverse_dataset_advice.append(model[0])
А почему это понадобилось? Согласно интерфейсу, super()._predict_single() должен вернуть список моделей с одним уровнем вложенности. Если это не так, надо фиксить метод в super()

2023-10-28 08:58 UTC, nicl-nno commented on meta_automl/meta_algorithm/model_advisors/diverse_fedot_pipeline_advisor.py
> +                diverse_dataset_advice.append(model[0])
Я пока просто запускал все примеры по порядку и ловил ошибку. У тебя пример "advise_models_from_similar_datasets.py" отрабатывает без этого фикса?

2023-10-29 13:13 UTC, MorrisNein commented on meta_automl/meta_algorithm/model_advisors/diverse_fedot_pipeline_advisor.py
> +                diverse_dataset_advice.append(model[0])
Действительно была ошибка, залил фикс

2023-10-29 13:15 UTC, MorrisNein approved these changes

2023-10-29 22:53 UTC, merged