Fix common issues
ITMO-NSS-team/GAMLET pull request #68
Opened 2023-11-01 00:08 UTC by MorrisNein

Solves #16, #17, #53, #54, #65, #66, #67.

2023-11-01 00:08 UTC, pep8speaks commented
Hello @MorrisNein! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`examples/3_selecting_similar_datasets/select_similar_ts_by_knn.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/3d7808d0829923d0ac9f618be279c5be1fec3310/examples/3_selecting_similar_datasets/select_similar_ts_by_knn.py):

> [Line 24:121](https://github.com/ITMO-NSS-team/GAMLET/blob/3d7808d0829923d0ac9f618be279c5be1fec3310/examples/3_selecting_similar_datasets/select_similar_ts_by_knn.py#L24): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (131 > 120 characters)











* In the file [`meta_automl/data_preparation/meta_features_extractors/pymfe_extractor.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/3d7808d0829923d0ac9f618be279c5be1fec3310/meta_automl/data_preparation/meta_features_extractors/pymfe_extractor.py):

> [Line 3:1](https://github.com/ITMO-NSS-team/GAMLET/blob/3d7808d0829923d0ac9f618be279c5be1fec3310/meta_automl/data_preparation/meta_features_extractors/pymfe_extractor.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'logging' imported but unused



* In the file [`meta_automl/meta_algorithm/dataset_similarity_assessors/__init__.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/3d7808d0829923d0ac9f618be279c5be1fec3310/meta_automl/meta_algorithm/dataset_similarity_assessors/__init__.py):

> [Line 1:1](https://github.com/ITMO-NSS-team/GAMLET/blob/3d7808d0829923d0ac9f618be279c5be1fec3310/meta_automl/meta_algorithm/dataset_similarity_assessors/__init__.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) '.dataset_similarity_assessor.DatasetSimilarityAssessor' imported but unused
> [Line 2:1](https://github.com/ITMO-NSS-team/GAMLET/blob/3d7808d0829923d0ac9f618be279c5be1fec3310/meta_automl/meta_algorithm/dataset_similarity_assessors/__init__.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) '.model_based_similarity_assessors.KNeighborsSimilarityAssessor' imported but unused
> [Line 2:1](https://github.com/ITMO-NSS-team/GAMLET/blob/3d7808d0829923d0ac9f618be279c5be1fec3310/meta_automl/meta_algorithm/dataset_similarity_assessors/__init__.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) '.model_based_similarity_assessors.ModelBasedSimilarityAssessor' imported but unused





* In the file [`meta_automl/meta_algorithm/model_advisors/__init__.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/3d7808d0829923d0ac9f618be279c5be1fec3310/meta_automl/meta_algorithm/model_advisors/__init__.py):

> [Line 1:1](https://github.com/ITMO-NSS-team/GAMLET/blob/3d7808d0829923d0ac9f618be279c5be1fec3310/meta_automl/meta_algorithm/model_advisors/__init__.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'meta_automl.meta_algorithm.model_advisors.model_advisor.DatasetSimilarityModelAdvisor' imported but unused
> [Line 1:1](https://github.com/ITMO-NSS-team/GAMLET/blob/3d7808d0829923d0ac9f618be279c5be1fec3310/meta_automl/meta_algorithm/model_advisors/__init__.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'meta_automl.meta_algorithm.model_advisors.model_advisor.ModelAdvisor' imported but unused
> [Line 2:1](https://github.com/ITMO-NSS-team/GAMLET/blob/3d7808d0829923d0ac9f618be279c5be1fec3310/meta_automl/meta_algorithm/model_advisors/__init__.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) 'meta_automl.meta_algorithm.model_advisors.diverse_model_advisor.DiverseModelAdvisor' imported but unused
> [Line 3:1](https://github.com/ITMO-NSS-team/GAMLET/blob/3d7808d0829923d0ac9f618be279c5be1fec3310/meta_automl/meta_algorithm/model_advisors/__init__.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'meta_automl.meta_algorithm.model_advisors.surrogate_advisor.SurrogateGNNPipelineAdvisor' imported but unused

2023-11-01 09:19 UTC, ShikovEgor reviewed
В /experiments/base хранились чекпоинты обученной модели для использования в дальнейшем. Название директорий так себе, но на мой взгляд в /data им тоже не место.
Предлагаю создать директорию model_checkpoints (либо model_weights) в корне. Примерная структура:
_model_checkpoinst_
______ _table_data_
____________ _checkpoints_
____________ events.out.tfevents…..
____________ hparams.yaml
______ _timeseries_
                .....

2023-11-02 15:18 UTC, ShikovEgor approved these changes

2023-11-09 07:40 UTC, valer1435 requested changes

2023-11-09 07:40 UTC, valer1435 commented on examples/6_inference/inference_ts_knn.py
> +    mf_train, mf_test = train_test_split(meta_features, train_size=0.75, random_state=42)
Здесь тогда тоже можно разделить вместе с индексом сразу

2023-11-09 07:40 UTC, valer1435 commented on meta_automl/data_preparation/meta_features_extractors/pymfe_extractor.py
> +                most_frequent = x_new[col].value_counts(sort=True, ascending=False).values[0]
Мб информация о том, что не удалось посчитать данный признак более информативна, чем просто заменить все на моду и медиану?

2023-11-09 07:40 UTC, valer1435 commented on meta_automl/data_preparation/meta_features_extractors/time_series/time_series_meta_features_extractor.py
> +                with IndustrialModels():
Это лучше перенести вне цикла, чтобы не вызывать каждый раз тяжелую операцию подгрузки репозитория

2023-11-09 17:44 UTC, MorrisNein commented on meta_automl/data_preparation/meta_features_extractors/pymfe_extractor.py
> +                most_frequent = x_new[col].value_counts(sort=True, ascending=False).values[0]
Т.е. исключать целиком признак датасета из расчёта мета-признаков, если признак встречает none?

2023-11-09 18:06 UTC, MorrisNein commented on meta_automl/data_preparation/meta_features_extractors/time_series/time_series_meta_features_extractor.py
> +                with IndustrialModels():
Попробовал убрать, всё работает. Контекст оказался нужен только при загрузке пайплайна

2023-11-09 18:07 UTC, MorrisNein commented on examples/6_inference/inference_ts_knn.py
> +    mf_train, mf_test = train_test_split(meta_features, train_size=0.75, random_state=42)
Сделал

2023-11-09 18:07 UTC, MorrisNein commented on meta_automl/data_preparation/meta_features_extractors/pymfe_extractor.py
> +                most_frequent = x_new[col].value_counts(sort=True, ascending=False).values[0]
Пока что заменил на более лаконичный расчёт моды

2023-11-10 12:50 UTC, valer1435 commented on meta_automl/data_preparation/meta_features_extractors/pymfe_extractor.py
> +                most_frequent = x_new[col].value_counts(sort=True, ascending=False).values[0]
Нет. Я имел ввиду, что мы можем заменить нан на какое-то специальное значение, которое будет говорить о том, что значения там нет. 

Но такое значение, чтобы модель смогла переварить

2023-11-10 12:52 UTC, valer1435 commented on meta_automl/data_preparation/meta_features_extractors/pymfe_extractor.py
> +                fill_value = x_new[col].median(skipna=True)
Можно оставить и как было. Про замену нанов каким-то специфичным значением просто идея

2023-11-10 12:52 UTC, valer1435 approved these changes

2023-11-10 13:51 UTC, merged