Issue 73
ITMO-NSS-team/GAMLET pull request #80
Opened 2023-11-15 22:02 UTC by ChernyakKonstantin

Apply changes suggested in issue #73 

There is also small reformatting and documentation extension.

2023-11-15 22:05 UTC, ChernyakKonstantin commented
I need some help on the `examples/4_advising_models/advise_by_surrogate.py` example testing.

My current version of PyTorch is 2.1.0 that is not compatible with surrogate model.

Who can run the example, please, report whether it works properly. Otherwise, provide me version of PyTorch that you have if you can run the example.

2023-11-22 11:55 UTC, MorrisNein requested changes
Идём верным курсом, спасибо! Осталось немного

2023-11-22 11:55 UTC, MorrisNein commented on examples/4_advising_models/advise_by_surrogate.py
Тут лучше всё-таки использовать функции из `meta_automl.data_preparation.file_system.file_system`, чтобы не отталкиваться от местоположения скрипта.

2023-11-22 11:55 UTC, MorrisNein commented on meta_automl/meta_algorithm/model_advisors/surrogate_advisor.py
> +
Одна из основных идей этой issue как раз вынести эти действия вовне, чтобы принимать на вход их результат. Сделаешь, пожалуйста?

Организацию взаимосвязи компонентов для конкретных задач планируется вынести в отдельный класс MetaLearningApproach

2023-11-22 13:31 UTC, ChernyakKonstantin commented
> Идём верным курсом, спасибо! Осталось немного

Удалось проверить пример на работоспособность?

2023-11-24 11:08 UTC, pep8speaks commented
Hello @ChernyakKonstantin! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`meta_automl/meta_algorithm/model_advisors/__init__.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/f761c309536a46b80c89fc3dee2eb1627eac2638/meta_automl/meta_algorithm/model_advisors/__init__.py):

> [Line 1:1](https://github.com/ITMO-NSS-team/GAMLET/blob/f761c309536a46b80c89fc3dee2eb1627eac2638/meta_automl/meta_algorithm/model_advisors/__init__.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'meta_automl.meta_algorithm.model_advisors.model_advisor.DatasetSimilarityModelAdvisor' imported but unused
> [Line 1:1](https://github.com/ITMO-NSS-team/GAMLET/blob/f761c309536a46b80c89fc3dee2eb1627eac2638/meta_automl/meta_algorithm/model_advisors/__init__.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'meta_automl.meta_algorithm.model_advisors.model_advisor.ModelAdvisor' imported but unused
> [Line 2:1](https://github.com/ITMO-NSS-team/GAMLET/blob/f761c309536a46b80c89fc3dee2eb1627eac2638/meta_automl/meta_algorithm/model_advisors/__init__.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) 'meta_automl.meta_algorithm.model_advisors.diverse_model_advisor.DiverseModelAdvisor' imported but unused
> [Line 3:1](https://github.com/ITMO-NSS-team/GAMLET/blob/f761c309536a46b80c89fc3dee2eb1627eac2638/meta_automl/meta_algorithm/model_advisors/__init__.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'meta_automl.meta_algorithm.model_advisors.surrogate_advisor.SurrogateGNNModelAdvisor' imported but unused

2023-11-24 11:08 UTC, MorrisNein commented
> Удалось проверить пример на работоспособность?

Да, с небольшими фиксами запустил.

2023-11-24 11:11 UTC, ChernyakKonstantin commented
> Да, с небольшими фиксами запустил.

Напиши версию pytorch и PyTorch_geometric, с которыми удалось запустить.

2023-11-24 11:19 UTC, MorrisNein commented on meta_automl/meta_algorithm/model_advisors/surrogate_advisor.py
> +
> А не сильно усложняется схема

Нет, норм. Так гораздо проще разрабатывать и дебажить, когда на каждом компоненте лежит только одна задача.

Более того, я предлагаю вынести unpickling пайплайнов из адвайзора -- это не его зона ответственности. Вместо этого он может подавать на выход предикта скоры и индексы.

Чтобы упростить использование, нужно не усложнять компоненты, а использовать для шаблонов их взаимодействия другие классы

2023-11-24 11:21 UTC, MorrisNein commented
> Напиши версию pytorch и PyTorch_geometric, с которыми удалось запустить.

```
(venv) pshevchenko@ruthenium:/var/essdata/GAMLET$ pip freeze | grep torch
pytorch-lightning==2.0.5
torch==2.0.0+cpu
torch-geometric==2.3.0
torch-scatter==2.1.2+pt20cpu
torchmetrics==0.11.4
torchvision==0.15.1+rocm5.4.2
```

2023-12-07 18:49 UTC, ChernyakKonstantin commented on meta_automl/meta_algorithm/model_advisors/surrogate_advisor.py
> +        datasets_features: List[Data],
Я внес изменения.
Однако, подача в качестве аргументов как самих датасетов и пайплайнов, так и их признаков, на мой взгляд, выглядит несколько контр-интуитивной.

2023-12-13 11:44 UTC, MorrisNein approved these changes

2023-12-13 11:44 UTC, MorrisNein commented on examples/4_advising_models/advise_by_surrogate.py
> +Run this module from the repo root.
Это уже не актуально, так как мы прописали абсолютные пути

2023-12-13 11:44 UTC, MorrisNein commented on meta_automl/meta_algorithm/model_advisors/surrogate_advisor.py
> +
Я о том, чтобы не подавать объектами датасеты и пайплайны на вход. Тогда этот класс не будет обязан собирать модели. Ему достаточно будет указать на то, какие индексы пайплайнов подходят для датасетов по списку.

Но в целом, это можно сделать и за рамками этого PR.

2023-12-13 12:12 UTC, MorrisNein commented
Пофиксил конфликты, вызванные моими недавними правками. Также адаптировал пример

2023-12-14 09:42 UTC, ShikovEgor approved these changes

2023-12-15 10:38 UTC, ChernyakKonstantin commented on meta_automl/meta_algorithm/model_advisors/surrogate_advisor.py
> +
Да, давай в отдельный PR. Это же редактор predict_single метода?

2023-12-15 12:21 UTC, merged