Timeseries surrogate
ITMO-NSS-team/GAMLET pull request #85
Opened 2023-11-28 13:48 UTC by ShikovEgor

What's new:
- Unification of meta-dataset file construction for surrogate model training for table and timeseries data.
- Rework of the training code.
- Fix quality metrics and data sampling, taking into account the difference in number of pipelines for different datasets.
- Added checkpoints and configes for timeseries.

2023-11-28 13:48 UTC, pep8speaks commented
Hello @ShikovEgor! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`meta_automl/data_preparation/models_loaders/__init__.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/__init__.py):

> [Line 1:1](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/__init__.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) '.models_loader.ModelsLoader' imported but unused
> [Line 2:1](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/__init__.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) '.fedot_pipelines_loader.FEDOTPipelinesLoader' imported but unused
> [Line 3:1](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/__init__.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) '.knowledge_base_models_loader.KnowledgeBaseModelsLoader' imported but unused
> [Line 3:1](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/__init__.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) '.knowledge_base_models_loader.KBTSModelsLoader' imported but unused

* In the file [`meta_automl/data_preparation/models_loaders/fedot_pipelines_loader.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/fedot_pipelines_loader.py):

> [Line 13:50](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/fedot_pipelines_loader.py#L13): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

* In the file [`meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py):

> [Line 47:81](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L47): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 47:81](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L47): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 50:1](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L50): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 56:69](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L56): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 59:1](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L59): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 63:34](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L63): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 66:40](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L66): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 66:63](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L66): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 66:73](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L66): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before ')'
> [Line 66:75](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L66): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 69:1](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L69): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 126:23](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L126): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 127:26](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L127): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 128:30](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L128): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 128:32](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L128): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 131:1](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L131): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 137:63](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L137): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 138:39](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L138): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 139:45](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L139): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 141:54](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L141): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 144:1](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L144): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 145:1](https://github.com/ITMO-NSS-team/GAMLET/blob/a9128c02bef496b253d9804c5dc18cfd2ebbaa12/meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py#L145): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 146:5](https://gith [...]

2023-11-29 13:54 UTC, valer1435 approved these changes

2023-12-18 07:30 UTC, MorrisNein requested changes

2023-12-18 07:30 UTC, MorrisNein commented on meta_automl/surrogate/surrogate_model.py
А тут не стоит сделать `model_parameters.pop("pipe_encoder_type")`? Этот параметр должен подаваться в init?

2023-12-18 07:30 UTC, MorrisNein commented on meta_automl/surrogate/training/train_surrogate_model.py
> +    )
Что означает is_pair?

2023-12-18 07:30 UTC, MorrisNein commented on meta_automl/surrogate/training/train_surrogate_model.py
> +    # trainer.test(model, dataloaders=test_loader)
Можно удалить?

2023-12-18 07:30 UTC, MorrisNein commented on meta_automl/surrogate/training/tune_surrogate_model.py
> +from .train_surrogate_model import (
Зачем здесь относительный импорт? Лучше их избегать

2023-12-18 07:30 UTC, MorrisNein commented on meta_automl/surrogate/training/tune_surrogate_model.py
> +    #     config["batch_norm"],
Можно удалить?

2023-12-18 07:30 UTC, MorrisNein commented on meta_automl/surrogate/training/tune_surrogate_model.py
> +    # config["gnn_type"] = trial.suggest_categorical("gnn_type", [x for x in config["gnn_type"]])
Можно удалить?

2023-12-18 07:30 UTC, MorrisNein commented on scripts/generate_training_dataset.py
> +        dataset_directory=get_data_dir() / "timeseries",  # pymfe_meta_features_and_fedot_pipelines
Возможно, стоит сделать отдельный скрипт, вместо того чтобы хранить предыдущие значения в комментариях?

2023-12-18 07:30 UTC, MorrisNein commented on scripts/generate_training_dataset.py
> +    # converter.convert_datasets()
Можно удалить?

2023-12-18 07:32 UTC, MorrisNein commented
Также обратите внимание на падающий юнит тест. Где-то нужно перепроверить путь к файлу и заменить на путь с использованием функций из file_system.py

2023-12-18 07:53 UTC, MorrisNein commented
И всё-таки, покройте используемые классы и функции минимальными юнит-тестами на работоспособность на минимальном подмножестве данных, которые можно сохранить в tests/data. Это убережёт ваш код от вымирания с каждым последующим PR.

2023-12-18 08:49 UTC, ShikovEgor commented
Не могу пока пофиксить:
python scripts/main.py --train --config configs/train_surrogate_TS.yml
Traceback (most recent call last):
  File "/data/home/egor/GAMLET/scripts/main.py", line 5, in <module>
    from meta_automl.surrogate import training
  File "/data/home/egor/GAMLET/meta_automl/surrogate/training/__init__.py", line 1, in <module>
    from .train_surrogate_model import train_surrogate_model, test_ranking
  File "/data/home/egor/GAMLET/meta_automl/surrogate/training/train_surrogate_model.py", line 22, in <module>
    from meta_automl.data_preparation.surrogate_dataset import GraphDataset, PairDataset, SingleDataset
  File "/data/home/egor/GAMLET/meta_automl/data_preparation/surrogate_dataset/__init__.py", line 2, in <module>
    from .dataset_generate import (
  File "/data/home/egor/GAMLET/meta_automl/data_preparation/surrogate_dataset/dataset_generate.py", line 16, in <module>
    from meta_automl.data_preparation.feature_preprocessors import FeaturesPreprocessor
  File "/data/home/egor/GAMLET/meta_automl/data_preparation/feature_preprocessors/__init__.py", line 1, in <module>
    from .feature_preprocessors import FeaturesPreprocessor
  File "/data/home/egor/GAMLET/meta_automl/data_preparation/feature_preprocessors/feature_preprocessors.py", line 9, in <module>
    from meta_automl.data_preparation.meta_features_extractors.dataset_meta_features import DatasetMetaFeatures
  File "/data/home/egor/GAMLET/meta_automl/data_preparation/meta_features_extractors/__init__.py", line 2, in <module>
    from .openml_dataset_meta_features_extractor import OpenMLDatasetMetaFeaturesExtractor
  File "/data/home/egor/GAMLET/meta_automl/data_preparation/meta_features_extractors/openml_dataset_meta_features_extractor.py", line 7, in <module>
    from meta_automl.data_preparation.feature_preprocessors import FeaturesPreprocessor
ImportError: cannot import name 'FeaturesPreprocessor' from partially initialized module 'meta_automl.data_preparation.feature_preprocessors' (most likely due to a circular import) (/data/home/egor/GAMLET/meta_automl/data_preparation/feature_preprocessors/__init__.py)
(new) [egor@bb565d71c869 GAMLET]$

2023-12-18 11:58 UTC, MorrisNein commented
> Не могу пока пофиксить: ...

Готово. Но лучше совсем уберите `FeaturesPreprocessor` из `OpenMLDatasetMetaFeaturesExtractor`.

2023-12-19 09:01 UTC, MorrisNein commented
Пофиксил конфликты повторно

2023-12-22 10:19 UTC, ShikovEgor commented on meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py
> +                metadata['dataset_id'] = d_id
Сейчас сложно вспомнить, в чем была идея. На данный момент данное изменение не нужно.

2023-12-22 10:22 UTC, ShikovEgor commented on meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py
>      return models
Коэффициент -1 нужен для того, что исторически в суррогате мы использовали некий "score", а не "fitness". При этом предполагали, что чем больше score - тем лучше пайплайн. Можно перейти к fitness в суррогате, но это на мой взгляд нужно делать отдельным PR, т.к много мелочей придется проверить.

2023-12-22 10:23 UTC, ShikovEgor commented on meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py
> +    def __init__(self,
можно в дальнейшем убрать его

2023-12-22 10:23 UTC, ShikovEgor commented on meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py
> +        # df_knowledge_base['dataset_cache'] = df_knowledge_base['dataset_id'].map(cached_datasets)
ок

2023-12-22 10:27 UTC, ShikovEgor commented on meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py
>  import logging
Возможно. А изначально ты ее писал?

2023-12-22 10:28 UTC, ShikovEgor commented on meta_automl/data_preparation/surrogate_dataset/data.py
> +        # self.weights = 1./cnts  # dataset weight
Эти части в процессе разработки. Поэтому многое может еще поменяться. Возможно, будем использовать закомменченный код в дальнейшем.

2023-12-22 10:32 UTC, ShikovEgor commented on meta_automl/data_preparation/surrogate_dataset/data.py
> +        self.task_pipe_dict = self.indxs.groupby("task_id")["ind"].apply(list).to_dict()  # .apply(lambda x: x[:20])
уберу

2023-12-22 10:32 UTC, ShikovEgor commented on meta_automl/data_preparation/surrogate_dataset/data.py
> +        # w = torch.tensor(self.weights[task_id], dtype=torch.float32)
может пригодится

2023-12-22 10:33 UTC, ShikovEgor commented on meta_automl/data_preparation/surrogate_dataset/dataset_generate.py
>          # if isinstance(datasets_meta_features[0], pd.DataFrame):
нет. уберу

2023-12-22 10:33 UTC, ShikovEgor commented on meta_automl/surrogate/encoders/dataset_encoder.py
> +            # nn.BatchNorm1d(hidden_dim),
уберу

2023-12-22 10:33 UTC, ShikovEgor commented on meta_automl/surrogate/encoders/dataset_encoder.py
> +        # z = self.inp_layer(data.x)
нет

2023-12-22 10:47 UTC, ShikovEgor commented on meta_automl/surrogate/surrogate_model.py
да вроде и так нормально

2023-12-22 10:47 UTC, ShikovEgor commented on meta_automl/surrogate/surrogate_model.py
> +        # print(results2.groupby("stype").ndcg.mean())
уберу

2023-12-22 10:48 UTC, ShikovEgor commented on meta_automl/surrogate/training/train_surrogate_model.py
> +    task_sets = train_val_test_split(splits, tasks_in_file, is_folded=config["dataset_params"]["is_folded"])
is_folded - если датасеты являются фолдами какого-то датасета

2023-12-22 10:49 UTC, ShikovEgor commented on meta_automl/surrogate/training/train_surrogate_model.py
> +    )
is_pair -  используется ли подход на основе пар пайплайнов для обучения. постараюсь написать комменты

2023-12-22 10:58 UTC, ShikovEgor commented on meta_automl/surrogate/training/tune_surrogate_model.py
> +    # config["gnn_type"] = trial.suggest_categorical("gnn_type", [x for x in config["gnn_type"]])
нет

2023-12-22 10:59 UTC, ShikovEgor commented on scripts/generate_training_dataset.py
> +        dataset_directory=get_data_dir() / "timeseries",  # pymfe_meta_features_and_fedot_pipelines
Думаю, нужно прописать это как параметры командной строки. Просто времени не было

2023-12-22 10:59 UTC, ShikovEgor commented on scripts/generate_training_dataset.py
> +    # converter.convert_datasets()
да, удалю

2023-12-22 10:59 UTC, ShikovEgor commented on meta_automl/surrogate/training/train_surrogate_model.py
> +    # trainer.test(model, dataloaders=test_loader)
да, удалю

2023-12-22 11:00 UTC, ShikovEgor commented on meta_automl/surrogate/training/tune_surrogate_model.py
> +    #     config["batch_norm"],
да, удалю

2023-12-22 14:06 UTC, MorrisNein commented on scripts/generate_training_dataset.py
> +        dataset_directory=get_data_dir() / "timeseries",  # pymfe_meta_features_and_fedot_pipelines
Лучше тогда в конфиг файл, если можно. Будет удобнее запускать

2023-12-22 14:08 UTC, MorrisNein commented on meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py
>  import logging
Я писал, но дело даже не в этом. У нас база версии "0" хранится прямо в репозитории. Хорошо бы оставить возможность и её открывать тоже, иначе она становится мёртвым грузом.

Или, возможно, разумно её удалить

2024-01-08 17:07 UTC, ShikovEgor commented on meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py
>  import logging
Добавил класс CompatKBModelsLoader для совместимости в дополнение к базовому коду.

2024-01-09 16:32 UTC, MorrisNein commented on meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py
> +        models.append(EvaluatedModel(predictor, metric_value, fitness_metric, None, metadata))  # row['dataset_cache']
@ShikovEgor тут осталось без изменений

2024-01-09 16:33 UTC, MorrisNein commented on meta_automl/data_preparation/surrogate_dataset/dataset_generate.py
> +            self.models_loader = KBTSModelsLoader(self.knowledge_base_directory)
Тут тоже без изменений. Оставим так?

2024-01-09 16:38 UTC, MorrisNein commented on meta_automl/surrogate/training/train_surrogate_model.py
> +    datasets, task_pipe_comb, pipelines, splits = get_files(
Так что же это означает?)

2024-01-09 16:42 UTC, MorrisNein commented on scripts/generate_training_dataset.py
> +    # converter.convert_datasets()
Эта строчка осталась

2024-01-11 12:12 UTC, ShikovEgor commented on meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py
> +        models.append(EvaluatedModel(predictor, metric_value, fitness_metric, None, metadata))  # row['dataset_cache']
@MorrisNein  здесь не разобрался, что нужно сделать, напишу тебе.

2024-01-11 12:13 UTC, ShikovEgor commented on meta_automl/data_preparation/surrogate_dataset/dataset_generate.py
> +            self.models_loader = KBTSModelsLoader(self.knowledge_base_directory)
Предлагаю оставить. Думаю, в будущем сведем загрузчик к одному классу, как ты и предлагал. И изменения в этом коде будут просто не нужны.

2024-01-11 12:31 UTC, ShikovEgor commented on meta_automl/surrogate/training/train_surrogate_model.py
> +    datasets, task_pipe_comb, pipelines, splits = get_files(
Таблица: pipeline_id / dataset_id /quality value. Добавил расшифровку в функцию get_files.

2024-01-11 12:33 UTC, ShikovEgor commented on scripts/generate_training_dataset.py
> +    # converter.convert_datasets()
ой. я ее откомментил сейчас

2024-01-11 13:07 UTC, MorrisNein commented on meta_automl/surrogate/training/train_surrogate_model.py
> +    datasets, task_pipe_comb, pipelines, splits = get_files(
Мне кажется, по смыслу похоже на `pipeline_evaluation`. Мб использовать это наименование?

2024-01-11 13:17 UTC, MorrisNein commented on meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py
> +        models.append(EvaluatedModel(predictor, metric_value, fitness_metric, None, metadata))  # row['dataset_cache']
Заменить None на `<DatasetClass>(row['dataset_id'])`

2024-01-11 14:13 UTC, ShikovEgor commented on meta_automl/surrogate/training/train_surrogate_model.py
> +    datasets, task_pipe_comb, pipelines, splits = get_files(
Можно и так. Я хотел подчеркнуть, что ключевыми здесь являются комбинации пайплайн-датасет. При рекомендации пайплайнов для нового датасета мы не знаем значения метрики.  Но выбираем определенный набор пайплайнов и считаем его для конкретного датасета.

2024-01-11 16:11 UTC, MorrisNein commented on meta_automl/surrogate/training/train_surrogate_model.py
> +    datasets, task_pipe_comb, pipelines, splits = get_files(
Тогда `pipeline_task_pairs`?

2024-01-11 23:38 UTC, MorrisNein approved these changes

2024-01-15 13:23 UTC, ShikovEgor commented on meta_automl/data_preparation/models_loaders/knowledge_base_models_loader.py
> +        models.append(EvaluatedModel(predictor, metric_value, fitness_metric, None, metadata))  # row['dataset_cache']
исправил

2024-01-15 13:24 UTC, ShikovEgor commented on meta_automl/surrogate/training/train_surrogate_model.py
> +    datasets, task_pipe_comb, pipelines, splits = get_files(
можно и так. на мой взгляд не принципиально

2024-01-20 17:20 UTC, merged