bump to new fedot ind version
ITMO-NSS-team/GAMLET pull request #97
Opened 2024-02-21 12:29 UTC by valer1435

bump to new fedot ind version

2024-02-21 12:29 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`gamlet/components/meta_features_extractors/time_series/time_series_meta_features_extractor.py`](https://github.com/ITMO-NSS-team/GAMLET/blob/d9230c0b81c8535041016fb1972d23931999cc37/gamlet/components/meta_features_extractors/time_series/time_series_meta_features_extractor.py):

> [Line 5:1](https://github.com/ITMO-NSS-team/GAMLET/blob/d9230c0b81c8535041016fb1972d23931999cc37/gamlet/components/meta_features_extractors/time_series/time_series_meta_features_extractor.py#L5): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.pipelines.pipeline.Pipeline' imported but unused
> [Line 14:1](https://github.com/ITMO-NSS-team/GAMLET/blob/d9230c0b81c8535041016fb1972d23931999cc37/gamlet/components/meta_features_extractors/time_series/time_series_meta_features_extractor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'gamlet.data_preparation.file_system.get_project_root' imported but unused

2024-02-21 12:33 UTC, valer1435 commented
![image](https://github.com/ITMO-NSS-team/GAMLET/assets/32017472/e46aec07-65c1-412b-a3b7-4b3d73dbc64c)

2024-02-22 06:56 UTC, MorrisNein requested changes

2024-02-22 06:56 UTC, MorrisNein commented on gamlet/components/meta_features_extractors/time_series/time_series_meta_features_extractor.py
> +        pipeline.fit(input_data)
Почему компонент теперь обучается на рандомных данных?

2024-05-20 16:04 UTC, merged